## Binomial Model (Slide 9-12) #
Consider a binomial model with 2 states of nature : **Up (U) and Down (D)**
* Risky stock has initial price of S, which can either rise to uS
or drop to dS, where $u > d$ (this is from QF620)
* Riskless bond has initial price of $P_f = {R_f}^{-1}$ where $u > R_f > d $
* Recall : Riskless bond  is something that gives a return $X_f$ = 1 **regardless of state** at time = $T$, so the return is 1 over the price of the bond , i.e. $R_f = {P_f}^{-1}$
$$
\mathbf{P} =
\begin{bmatrix}
S\\
P_f
\end{bmatrix}
,
\mathbf{X} =
\begin{bmatrix}
uS  &   1\\
ds  &   1\\
\end{bmatrix}
$$

We can the construct the following :
1. Vector of state prices
$$
\begin{bmatrix}
p_u  & p_d
\end{bmatrix} =
\mathbf{P}^\intercal \mathbf{X}^{-1}
$$

2. Vector of risk neutral probabilities
$$
\begin{bmatrix}
\hat{\pi_u}  & \hat{\pi_d} 
\end{bmatrix} =
R_f \begin{bmatrix}
p_u  & p_d
\end{bmatrix}
$$

3. Pricing formula for a portfolio that delivers $Y_u$ and $Y_d$
$$
\mathbf{Y} =
\begin{bmatrix}
Y_u  \\ Y_d 
\end{bmatrix}\\
$$
$$
P_Y = \begin{bmatrix}
p_u  & p_d
\end{bmatrix}\begin{bmatrix}
Y_u  \\ Y_d 
\end{bmatrix}
=
\frac{1}{R_f}
\begin{bmatrix}
\hat{\pi_u}  & \hat{\pi_d} 
\end{bmatrix}
\begin{bmatrix}
Y_u  \\ Y_d 
\end{bmatrix}
$$

Economic significance of #3 : Pricing using the risk-free measure will also work in real life because it is using state pricing in disguise. 

Recall from QF620, in case of binomial model, under risk-free measure, the expected value of stock at time $t+1$ should equal stock price at time $t$. 
$$

In [9]:
import numpy as np

In [2]:
# lets use values given by slides
def binomial_model(S: int, Rf: int, X_stock):
    """
    Binomial model

    Args:
        S (int): This is the stock price
        Rf (int): Risk free return (1+rf), NOT risk free rate
        X_stock (_type_): This is the payoff matrix for stock
    Returns:
        X : the payoff vector
        state_p: state prices vector
        risk_neutral_prob: risk neutral probability vector
    """
    X = np.column_stack((X_stock, [1, 1]))
    P = np.array([S, 1 / Rf])
    state_prices = np.dot(P, np.linalg.inv(X))
    risk_neutral_prob = Rf * state_prices
    return X, state_prices, risk_neutral_prob


def risky_payoff(S: int, *args):
    """
    Use this if you want to generate risky payoff with u & d

    Args:
        S (int): This is the stock price
        *args :
            args[0] = u
            args[1] = d, if not specified the d = 1/u
    """
    if len(args) == 1:
        u = args[0]
        d = 1 / u

    elif len(args) == 2:
        u = args[0]
        d = args[1]
    else:
        print("no args provided or more than 2 provided")
        return
    print(f"{u} and {d}")
    return np.array([u * S, d * S])

In [13]:
stock_payoff = risky_payoff(6, 5.0 / 3.0)
binomial_model(6, 1.05, stock_payoff)

1.6666666666666667 and 0.6


(array([[10. ,  1. ],
        [ 3.6,  1. ]]),
 array([0.40178571, 0.55059524]),
 array([0.421875, 0.578125]))

In [27]:
# test if correct, discounted expected final payoff should equal initial stock price under risk-free measure
payoff_final = (binomial_model(6, 1.05, stock_payoff)[0][:, 0],)
risk_free = binomial_model(6, 1.05, stock_payoff)[2]
(payoff_final * risk_free).sum() / 1.05

6.0

## State Prices Practice Problem ##

In [4]:
# Risk free return
Rf = 1.1
Pf = 1 / Rf

# stock price array = [P_A, P_B]
S = np.array([45, 45])

# sorted by [GOOD, NORMAL, BAD]
phys_prob = np.array([0.3, 0.5, 0.2])
X_A = np.array([75, 55, 20])
X_B = np.array([60, 50, 40])
X_RF = np.ones((len(phys_prob), 1))

# construct payoff, i put the risk free at the end
X = np.column_stack((X_A, X_B, X_RF))

# construct price, i also put the risk free at the end
P = np.append(S, Pf)

In [5]:
state_prices = np.dot(P, np.linalg.inv(X))
risk_neutral_prob = Rf * state_prices

Call option to buy one share of Stock A and one share of Stock B for 100

In [6]:
strike_price = 100

In [7]:
def option_payoff(x):
    if x < 0:
        return 0
    else:
        return x

In [8]:
vec_call_payoff = np.vectorize(option_payoff)
# final payoff vec
call_payoff = vec_call_payoff(X_A + X_B - strike_price)
# init price
call_price = np.dot(state_prices, call_payoff)
call_price

10.000000000000028